//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dictionary.DictionaryDA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnViEntities1 : DbContext
    {
        public EnViEntities1()
            : base("name=EnViEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ENWORD> ENWORDs { get; set; }
        public DbSet<idiom> idioms { get; set; }
        public DbSet<structure1> structure1 { get; set; }
        public DbSet<Verb> Verbs { get; set; }
        public DbSet<Favorite> Favorites { get; set; }
    }
}
