//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dictionary.DictionaryDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENWORD
    {
        public int ID { get; set; }
        public string EnWord1 { get; set; }
        public string Type { get; set; }
        public string EnVi { get; set; }
        public string Example { get; set; }
        public Nullable<int> Favote { get; set; }
    }
}
