//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dictionary.DictionaryDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Verb
    {
        public int ID { get; set; }
        public string First { get; set; }
        public string Second { get; set; }
        public string Thirst { get; set; }
        public string Meaning { get; set; }
    }
}
